# docker-compose.yaml
version: '3'
services:
 sonar:
  image: sonarqube:latest
  container_name: sonar
  ports:
   - 9000:9000
  volumes:
   - /home/sonarqube:/opt/sonarqube/data
  restart: on-failure
 nexus:
  image: sonatype/nexus3:latest
  container_name: nexus
  ports:
   - 8081:8081
   volumes:
   - /home/nexus-data:/sonatype-work
  restart: on-failure
  prometheus:
    image : prom/prometheus
    ports :
    - "9090:9090"
  grafana:
    image : grafana/grafana:latest
    ports :
    - "3000:3000"
