# docker-compose.yaml
version: '3'
services:
  nexus:
    image : sonatype/nexus3
    ports :
    - "8081:8081"
    volumes:
    - /home/nexus-data:/sonatype-work
    restart: on-failure
  prometheus:
    image : prom/prometheus
    ports :
    - "9090:9090"
  grafana:
    image : grafana/grafana:latest
    ports :
    - "3000:3000"
